import emoji from 'node-emoji';

let BASE_NBA_DATA_URL = "http://data.nba.com/";
let BASE_NBA_DATA_SCOREBOARD_URL = BASE_NBA_DATA_URL.concat("data/5s/json/cms/noseason/scoreboard/");
let BASE_NBA_DATA_PLAY_BY_PLAY_URL = BASE_NBA_DATA_URL.concat("data/5s/json/cms/noseason/game/");

let DEFAULT_DATE_FORMAT = "YYYYMMDD";
let DEFAULT_TIMEZONE = "America/New_York";

let TRANSLATED_NBA_DATE_TIME_FORMAT = "YYYYMMDDHHmm";
let TRANSLATED_DATE_FORMAT = "LLL";

let PREGAME = 'PREGAME';
let LIVE = 'LIVE';
let FINAL = 'FINAL';

let TRANSLATED_GAME_STATUS_MAP = {
  1: PREGAME,
  2: LIVE,
  3: FINAL,
};

let ONE_HUNDRED = 100;

let HOME_EMOJI_VALUE = 'house';
let VISITOR_EMOJI_VALUE = 'bus';
let START_TIME_EMOJI_VALUE = 'alarm_clock';
let BROADCASTS_EMOJI_VALUE = 'tv';
let SCORE_100_EMOJI_VALUE = '100';
let PLAY_TIME_EMOJI_VALUE = 'hourglass_flowing_sand';

let GAMES_OPTIONS = {
  TODAY: "TODAY",
  YESTERDAY: "YESTERDAY",
  TOMORROW: "TOMORROW"
};

const PLAY_TIME_EMOJI = emoji.get('hourglass_flowing_sand');

module.exports = {
  BASE_NBA_DATA_SCOREBOARD_URL: BASE_NBA_DATA_SCOREBOARD_URL,
  BASE_NBA_DATA_PLAY_BY_PLAY_URL: BASE_NBA_DATA_PLAY_BY_PLAY_URL,
  DEFAULT_DATE_FORMAT: DEFAULT_DATE_FORMAT,
  DEFAULT_TIMEZONE: DEFAULT_TIMEZONE,
  TRANSLATED_NBA_DATE_TIME_FORMAT: TRANSLATED_NBA_DATE_TIME_FORMAT,
  TRANSLATED_DATE_FORMAT: TRANSLATED_DATE_FORMAT,
  PREGAME: PREGAME,
  LIVE: LIVE,
  FINAL: FINAL,
  TRANSLATED_GAME_STATUS_MAP: TRANSLATED_GAME_STATUS_MAP,
  HOME_EMOJI_VALUE: HOME_EMOJI_VALUE,
  VISITOR_EMOJI_VALUE: VISITOR_EMOJI_VALUE,
  START_TIME_EMOJI_VALUE: START_TIME_EMOJI_VALUE,
  BROADCASTS_EMOJI_VALUE: BROADCASTS_EMOJI_VALUE,
  SCORE_100_EMOJI_VALUE: SCORE_100_EMOJI_VALUE,
  PLAY_TIME_EMOJI_VALUE: PLAY_TIME_EMOJI_VALUE,
  GAMES_OPTIONS: GAMES_OPTIONS,
  ONE_HUNDRED: ONE_HUNDRED,
  PLAY_TIME_EMOJI: PLAY_TIME_EMOJI,
};
