const ATLANTA_HAWKS = 'ATL';
const BOSTON_CELTICS = 'BOS';
const CLEVELAND_CAVALIERS = 'CLE';
const NEW_ORLEANS_PELICANS = 'NOP';
const CHICAGO_BULLS = 'CHI';
const DALLAS_MAVERICKS = 'DAL';
const DENVER_NUGGETS = 'DEN';
const GOLDEN_STATE_WARRIORS = 'GSW';
const HOUSTON_ROCKETS = 'HOU';
const LOS_ANGELES_CLIPPERS = 'LAC';
const LOS_ANGELES_LAKERS = 'LAL';
const MIAMI_HEAT = 'MIA';
const MILWAUKEE_BUCKS = 'MIL';
const MINNESOTA_TIMBERWOLVES = 'MIN';
const BROOKLYN_NETS = 'BKN';
const NEW_YORK_KNICKS = 'NYK';
const ORLANDO_MAGIC = 'ORL';
const INDIANA_PACERS = 'IND';
const PHILADELPHIA_76ERS = 'PHI';
const PHOENIX_SUNS = 'PHX';
const PORTLAND_TRAIL_BLAZERS = 'POR';
const SACRAMENTO_KINGS = 'SAC';
const SAN_ANTONIO_SPURS = 'SAS';
const OKLAHOMA_CITY_THUNDER = 'OKC';
const TORONTO_RAPTORS = 'TOR';
const MEMPHIS_GRIZZLIES = 'MEM';
const WASHINGTON_WIZARDS = 'WAS';
const DETROIT_PISTONS = 'DET';
const CHARLOTTE_HORNETS = 'CHA';
const UTAH_JAZZ = 'UTA';

const ABBREVIATIONS = [
  ATLANTA_HAWKS,
  BOSTON_CELTICS,
  CLEVELAND_CAVALIERS,
  NEW_ORLEANS_PELICANS,
  CHICAGO_BULLS,
  DALLAS_MAVERICKS,
  DENVER_NUGGETS,
  GOLDEN_STATE_WARRIORS,
  HOUSTON_ROCKETS,
  LOS_ANGELES_CLIPPERS,
  LOS_ANGELES_LAKERS,
  MIAMI_HEAT,
  MILWAUKEE_BUCKS,
  MINNESOTA_TIMBERWOLVES,
  BROOKLYN_NETS,
  NEW_YORK_KNICKS,
  ORLANDO_MAGIC,
  INDIANA_PACERS,
  PHILADELPHIA_76ERS,
  PHOENIX_SUNS,
  PORTLAND_TRAIL_BLAZERS,
  SACRAMENTO_KINGS,
  SAN_ANTONIO_SPURS,
  OKLAHOMA_CITY_THUNDER,
  TORONTO_RAPTORS,
  MEMPHIS_GRIZZLIES,
  WASHINGTON_WIZARDS,
  DETROIT_PISTONS,
  CHARLOTTE_HORNETS,
  UTAH_JAZZ
];

module.exports = {
  ATLANTA_HAWKS: ATLANTA_HAWKS,
  BOSTON_CELTICS: BOSTON_CELTICS,
  CLEVELAND_CAVALIERS: CLEVELAND_CAVALIERS,
  NEW_ORLEANS_PELICANS : NEW_ORLEANS_PELICANS,
  CHICAGO_BULLS : CHICAGO_BULLS,
  DALLAS_MAVERICKS : DALLAS_MAVERICKS,
  DENVER_NUGGETS : DENVER_NUGGETS,
  GOLDEN_STATE_WARRIORS: GOLDEN_STATE_WARRIORS,
  HOUSTON_ROCKETS : HOUSTON_ROCKETS,
  LOS_ANGELES_CLIPPERS : LOS_ANGELES_CLIPPERS,
  LOS_ANGELES_LAKERS : LOS_ANGELES_LAKERS,
  MIAMI_HEAT : MIAMI_HEAT,
  MILWAUKEE_BUCKS : MILWAUKEE_BUCKS,
  MINNESOTA_TIMBERWOLVES : MINNESOTA_TIMBERWOLVES,
  BROOKLYN_NETS : BROOKLYN_NETS,
  NEW_YORK_KNICKS : NEW_YORK_KNICKS,
  ORLANDO_MAGIC : ORLANDO_MAGIC,
  INDIANA_PACERS : INDIANA_PACERS,
  PHILADELPHIA_76ERS : PHILADELPHIA_76ERS,
  PHOENIX_SUNS : PHOENIX_SUNS,
  PORTLAND_TRAIL_BLAZERS : PORTLAND_TRAIL_BLAZERS,
  SACRAMENTO_KINGS : SACRAMENTO_KINGS,
  SAN_ANTONIO_SPURS : SAN_ANTONIO_SPURS,
  OKLAHOMA_CITY_THUNDER : OKLAHOMA_CITY_THUNDER,
  TORONTO_RAPTORS : TORONTO_RAPTORS,
  MEMPHIS_GRIZZLIES : MEMPHIS_GRIZZLIES,
  WASHINGTON_WIZARDS : WASHINGTON_WIZARDS,
  DETROIT_PISTONS : DETROIT_PISTONS,
  CHARLOTTE_HORNETS : CHARLOTTE_HORNETS,
  UTAH_JAZZ : UTAH_JAZZ,
  ABBREVIATIONS: ABBREVIATIONS
};